config/routes.rb
Rails.application.routes.draw do
  resources :question_types

  resources :quantifiers

  resources :users

  resources :games
  resources :answers
  resources :questions

  root 'users#index'

  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create", as: :sign_up
  get "/log-out" => "sessions#destroy", as: :log_out

  get "/get-user-api" => "users#api", as: :users_api

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id            :integer          not null, primary key
#  question_text :string(255)
#  description   :string(255)
#  location      :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  picture       :string(255)
#  game_id       :integer
#  question_type :string(255)
#  is_quantifier :boolean
#

class Question < ActiveRecord::Base

  has_many :answers, dependent: :destroy
  has_many :users, through: :answers

  belongs_to :game

  attr_accessor :picture
  mount_uploader :picture, PictureUploader

  validates :question_text, uniqueness: true

  def as_json(options)
    super(:only => [:question_text, :description, :location, :question_type])
  end

end

app/models/question_type.rb
# == Schema Information
#
# Table name: question_types
#
#  id         :integer          not null, primary key
#  type_text  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class QuestionType < ActiveRecord::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user, only: [:index]
  before_action :authenticate_admin, except: [:show, :index]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :xml
  def index
    @questions = Question.all
    if params.has_key?(:qtype)
      @questions = Question.where(:question_type => params[:qtype])
    end
    respond_with(@questions)
  end

  def show
    respond_with(@question)
  end

  def new
    @question = Question.new
    respond_with(@question)
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    #@question.save
    #respond_with(@question)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private

  def authenticate_admin

    if params.has_key?(:api_key)
      @user = ApiKey.find_by_key(params[:api_key]).user
      if @user && @user.isAdmin?
        return true
      end
    else
      return true if current_user.isAdmin?
    end
    error = {'error'=>'not authenticated'}.to_json
    render :json => error, status: :not_authorized
  end

  def authenticate_user
    if params.has_key?(:api_key)
      @user = ApiKey.find_by_key(params[:api_key]).user
      if @user
        return true
      end
    else
      if current_user
        return true
      end
    end
    error = {'error'=>'not authenticated'}.to_json
    render :json => error, status: :not_authorized
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:question_text, :description, :location, :picture, :question_type, :game_id, :is_quantifier)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => {:multipart => true} do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_text %><br>
    <%= f.text_field :question_text %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Question text</th>
      <th>Description</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question_text %></td>
        <td><%= question.description %></td>
        <td><%= question.location %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Question text:</strong>
  <%= @question.question_text %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @question.location %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@question.picture_url(:thumb)) if @question.picture.present? %>
</p>

<p>
  <strong>Answers:</strong>
  <% @question.answers.each do |f| %>
      <%= link_to f.answer_text, {:controller => "answers", :action => "show", :id => f.id} %>
  <% end %>
</p>
<%= link_to 'Answer', new_answer_path(:question_id => @question.id) %> |
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>