config/routes.rb
Rails.application.routes.draw do
  resources :question_types

  resources :quantifiers

  resources :users

  resources :games
  resources :answers
  resources :questions

  root 'users#index'

  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create", as: :sign_up
  get "/log-out" => "sessions#destroy", as: :log_out

  get "/get-user-api" => "users#api", as: :users_api

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id                        :integer          not null, primary key
#  user_id                   :integer
#  question_id               :integer
#  created_at                :datetime
#  updated_at                :datetime
#  answer_text               :string(255)
#  quantifier                :string(255)
#  location                  :string(255)
#  answer_image_file_name    :string(255)
#  answer_image_content_type :string(255)
#  answer_image_file_size    :integer
#  answer_image_updated_at   :datetime
#

class Answer < ActiveRecord::Base

  require 'socket'

  belongs_to :user
  belongs_to :question


  has_attached_file :answer_image,
                    :default_url => '',
                    :styles =>
                        {
                            :large    => ['800>',      :png, :quality => 90],
                            :retina   => ['1600>',     :png, :quality => 30]
                        },
                    :convert_options =>
                        {
                            :large    => '-set colorspace sRGB -strip',
                            :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
                        }
  validates_attachment_content_type :answer_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  def index
    @answers = Answer.all
    if params.has_key?(:user_id)
      @id = params[:user_id]
      @answers = Answer.where(:user_id => @id)
    elsif params.has_key?(:question_id)
      @answers = Answer.where(:question_id => params[:question_id])
    elsif params.has_key?(:quantifier)
      @answers = Answer.where(:quantifier => params[:quantifier])
    elsif params.has_key?(:question_id) && params.has_key?(:quantifier)
      @answers = Answer.where(:quantifier =>  params[:quantifier]) & Answer.where(:question_id => params[:question_id])
    elsif params.has_key?(:location) && params.has_key?(:quantifier)
      @answers = Answer.where(:quantifier =>  params[:quantifier]) & Answer.where(:location => params[:location])
    elsif params.has_key?(:location)
      @answers = Answer.where(:location => params[:location])
    end
    respond_with(@answers)
  end

  def show
    respond_with(@answer)
  end

  def new
    @answer = Answer.new
    respond_with(@answer)
  end

  def edit
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.save
    respond_with(@answer)
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    @answer.destroy
    respond_with(@answer)
  end

  private

  def authenticate_admin
    if params.has_key?(:api_key)
      @user = ApiKey.find_by_key(params[:api_key]).user
      if (@user) && (@user.isAdmin?)
        return true
      end
    else
      if (current_user) && (current_user.isAdmin?)
        return true
      end
    end
    error = {'error'=>'not authenticated'}.to_json
    render :json => error, status: :not_authorized
  end

  def authenticate_user
    if params.has_key?(:api_key)
      @user = ApiKey.find_by_key(params[:api_key]).user
      if @user
        return true
      end
    else
      if current_user
        return true
      end
    end
    error = {'error'=>'not authenticated'}.to_json
    render :json => error, status: :not_authorized
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:answer_text, :user_id, :question_id, :quantifier, :answer_image, :location)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
    <% if @answer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

          <ul>
            <% @answer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :answer_text %>
      <%= f.text_field :answer_text %>
    </div>
    <div class="field">
      <%= f.label :quantifier %>
      <%= f.collection_select :quantifier, Quantifier.order(:text),:text, :text, include_blank: false %>
    </div>

    <%= f.hidden_field :question_id, :value => params[:question_id]%>

    <div class="field">
      <%= f.label :answer_image %>
      <%= f.file_field :answer_image %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.answer_text %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Answer text:</strong>
  <%= @answer.answer_text %><br />
  <strong>Question ID:</strong>
  <%= link_to @answer.question_id, {:controller => "questions", :action => "show", :id => @answer.question_id} %><br />
  <strong>User ID:</strong>
  <%= @answer.user_id %>
  <strong>Picture:</strong>
  <%= image_tag @answer.answer_image.url(:large) %>
</p>
<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>