config/routes.rb
Rails.application.routes.draw do
  resources :question_types

  resources :quantifiers

  resources :users

  resources :games
  resources :answers
  resources :questions

  root 'users#index'

  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create", as: :sign_up
  get "/log-out" => "sessions#destroy", as: :log_out

  get "/get-user-api" => "users#api", as: :users_api

end

app/controllers/question_types_controller.rb
class QuestionTypesController < ApplicationController
  before_action :set_question_type, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  # GET /question_types
  # GET /question_types.json
  def index
    @question_types = QuestionType.all
  end

  # GET /question_types/1
  # GET /question_types/1.json
  def show
  end

  # GET /question_types/new
  def new
    @question_type = QuestionType.new
  end

  # GET /question_types/1/edit
  def edit
  end

  # POST /question_types
  # POST /question_types.json
  def create
    @question_type = QuestionType.new(question_type_params)

    respond_to do |format|
      if @question_type.save
        format.html { redirect_to @question_type, notice: 'Question type was successfully created.' }
        format.json { render :show, status: :created, location: @question_type }
      else
        format.html { render :new }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_types/1
  # PATCH/PUT /question_types/1.json
  def update
    respond_to do |format|
      if @question_type.update(question_type_params)
        format.html { redirect_to @question_type, notice: 'Question type was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_type }
      else
        format.html { render :edit }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_types/1
  # DELETE /question_types/1.json
  def destroy
    @question_type.destroy
    respond_to do |format|
      format.html { redirect_to question_types_url, notice: 'Question type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_type
      @question_type = QuestionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_type_params
      params.require(:question_type).permit(:type)
    end
end

app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

app/views/question_types/_form.html.erb
<%= form_for(@question_type) do |f| %>
  <% if @question_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_type.errors.count, "error") %> prohibited this question_type from being saved:</h2>

      <ul>
      <% @question_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_types/edit.html.erb
<h1>Editing question_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_type %> |
<%= link_to 'Back', question_types_path %>

app/views/question_types/index.html.erb
<h1>Listing question_types</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_types.each do |question_type| %>
      <tr>
        <td><%= question_type.type_text %></td>
        <td><%= link_to 'Show', question_type %></td>
        <td><%= link_to 'Edit', edit_question_type_path(question_type) %></td>
        <td><%= link_to 'Destroy', question_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question type', new_question_type_path %>

app/views/question_types/new.html.erb
<h1>New question_type</h1>

<%= render 'form' %>

<%= link_to 'Back', question_types_path %>

app/views/question_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @question_type.type %>
</p>

<%= link_to 'Edit', edit_question_type_path(@question_type) %> |
<%= link_to 'Back', question_types_path %>