config/routes.rb
Rails.application.routes.draw do
  resources :question_types

  resources :quantifiers

  resources :users

  resources :games
  resources :answers
  resources :questions

  root 'users#index'

  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create", as: :sign_up
  get "/log-out" => "sessions#destroy", as: :log_out

  get "/get-user-api" => "users#api", as: :users_api

end

app/models/quantifier.rb
# == Schema Information
#
# Table name: quantifiers
#
#  id         :integer          not null, primary key
#  text       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  game_id    :integer
#

class Quantifier < ActiveRecord::Base
end

app/controllers/quantifiers_controller.rb
class QuantifiersController < ApplicationController
  before_action :set_quantifier, only: [:show, :edit, :update, :destroy]

  # GET /quantifiers
  # GET /quantifiers.json
  def index
    @quantifiers = Quantifier.all
  end

  # GET /quantifiers/1
  # GET /quantifiers/1.json
  def show
  end

  # GET /quantifiers/new
  def new
    @quantifier = Quantifier.new
  end

  # GET /quantifiers/1/edit
  def edit
  end

  # POST /quantifiers
  # POST /quantifiers.json
  def create
    @quantifier = Quantifier.new(quantifier_params)

    respond_to do |format|
      if @quantifier.save
        format.html { redirect_to @quantifier, notice: 'Quantifier was successfully created.' }
        format.json { render :show, status: :created, location: @quantifier }
      else
        format.html { render :new }
        format.json { render json: @quantifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quantifiers/1
  # PATCH/PUT /quantifiers/1.json
  def update
    respond_to do |format|
      if @quantifier.update(quantifier_params)
        format.html { redirect_to @quantifier, notice: 'Quantifier was successfully updated.' }
        format.json { render :show, status: :ok, location: @quantifier }
      else
        format.html { render :edit }
        format.json { render json: @quantifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quantifiers/1
  # DELETE /quantifiers/1.json
  def destroy
    @quantifier.destroy
    respond_to do |format|
      format.html { redirect_to quantifiers_url, notice: 'Quantifier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quantifier
      @quantifier = Quantifier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quantifier_params
      params.require(:quantifier).permit(:text, :game_id)
    end
end

app/helpers/quantifiers_helper.rb
module QuantifiersHelper
end

app/views/quantifiers/_form.html.erb
<%= form_for(@quantifier) do |f| %>
  <% if @quantifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quantifier.errors.count, "error") %> prohibited this quantifier from being saved:</h2>

      <ul>
      <% @quantifier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quantifiers/edit.html.erb
<h1>Editing quantifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @quantifier %> |
<%= link_to 'Back', quantifiers_path %>

app/views/quantifiers/index.html.erb
<h1>Listing quantifiers</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quantifiers.each do |quantifier| %>
      <tr>
        <td><%= quantifier.text %></td>
        <td><%= link_to 'Show', quantifier %></td>
        <td><%= link_to 'Edit', edit_quantifier_path(quantifier) %></td>
        <td><%= link_to 'Destroy', quantifier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quantifier', new_quantifier_path %>

app/views/quantifiers/new.html.erb
<h1>New quantifier</h1>

<%= render 'form' %>

<%= link_to 'Back', quantifiers_path %>

app/views/quantifiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @quantifier.text %>
</p>

<%= link_to 'Edit', edit_quantifier_path(@quantifier) %> |
<%= link_to 'Back', quantifiers_path %>